

INSERT INTO PRODUCT (BRAND, PRICE, BRANCH_OFFICE_ID, CATEGORY_ID) 
VALUES ('SAVITAL', 8000, 2, 4);

INSERT INTO PRODUCT (BRAND, PRICE, BRANCH_OFFICE_ID, CATEGORY_ID) 
VALUES ('SAVITAL', 8000, 1, 5);

INSERT INTO PRODUCT (BRAND, PRICE, BRANCH_OFFICE_ID, CATEGORY_ID) 
VALUES ('SEDAL', 8000, 2, 6);

INSERT INTO PRODUCT (BRAND, PRICE, BRANCH_OFFICE_ID, CATEGORY_ID) 
VALUES ('SEDAL', 8000, 2, 7);

INSERT INTO PRODUCT (BRAND, PRICE, BRANCH_OFFICE_ID, CATEGORY_ID) 
VALUES ('SEDAL', 8000, 1, 9);

INSERT INTO PRODUCT (BRAND, PRICE, BRANCH_OFFICE_ID, CATEGORY_ID) 
VALUES ('SEDAL', 8000, 2, 1);

INSERT INTO PRODUCT (BRAND, PRICE, BRANCH_OFFICE_ID, CATEGORY_ID) 
VALUES ('PANTENE', 8000, 2, 9);

INSERT INTO PRODUCT (BRAND, PRICE, BRANCH_OFFICE_ID, CATEGORY_ID) 
VALUES ('PANTENE', 8000, 1, 8);

INSERT INTO PRODUCT (BRAND, PRICE, BRANCH_OFFICE_ID, CATEGORY_ID) 
VALUES ('PFIZER', 4000, 2, 1);

INSERT INTO PRODUCT (BRAND, PRICE, BRANCH_OFFICE_ID, CATEGORY_ID) 
VALUES ('FRITOLAY', 4000, 2, 4);

INSERT INTO PRODUCT (BRAND, PRICE, BRANCH_OFFICE_ID, CATEGORY_ID) 
VALUES ('FRITOLAY', 4000, 1, 5);

INSERT INTO PRODUCT (BRAND, PRICE, BRANCH_OFFICE_ID, CATEGORY_ID) 
VALUES ('LAGOMAR', 4000, 2, 6);

INSERT INTO PRODUCT (BRAND, PRICE, BRANCH_OFFICE_ID, CATEGORY_ID) 
VALUES ('MI LLANO', 6000, 2, 7);

INSERT INTO PRODUCT (BRAND, PRICE, BRANCH_OFFICE_ID, CATEGORY_ID) 
VALUES ('VANIPLAST', 25000, 1, 9);

INSERT INTO PRODUCT (BRAND, PRICE, BRANCH_OFFICE_ID, CATEGORY_ID) 
VALUES ('VANIPLAST', 25000, 2, 1);

INSERT INTO PRODUCT (BRAND, PRICE, BRANCH_OFFICE_ID, CATEGORY_ID) 
VALUES ('PLASTIHOGAR', 20000, 2, 2);

INSERT INTO PRODUCT (BRAND, PRICE, BRANCH_OFFICE_ID, CATEGORY_ID) 
VALUES ('ZEUS', 15000, 1, 8);

INSERT INTO PRODUCT (BRAND, PRICE, BRANCH_OFFICE_ID, CATEGORY_ID) 
VALUES ('MICHELIN', 15000, 2, 9);

INSERT INTO PRODUCT (BRAND, PRICE, BRANCH_OFFICE_ID, CATEGORY_ID) 
VALUES ('CARS', 15000, 2, 4);

INSERT INTO PRODUCT (BRAND, PRICE, BRANCH_OFFICE_ID, CATEGORY_ID) 
VALUES ('DONGATO', 25000, 1, 5);

INSERT INTO PRODUCT (BRAND, PRICE, BRANCH_OFFICE_ID, CATEGORY_ID) 
VALUES ('SPRITE', 5000, 2, 6);

INSERT INTO PRODUCT (BRAND, PRICE, BRANCH_OFFICE_ID, CATEGORY_ID) 
VALUES ('MANZANA', 5000, 2, 7);

INSERT INTO PRODUCT (BRAND, PRICE, BRANCH_OFFICE_ID, CATEGORY_ID) 
VALUES ('SPRITE', 10000, 1, 9);

INSERT INTO PRODUCT (BRAND, PRICE, BRANCH_OFFICE_ID, CATEGORY_ID) 
VALUES ('MANZANA', 10000, 2, 8);

INSERT INTO PRODUCT (BRAND, PRICE, BRANCH_OFFICE_ID, CATEGORY_ID) 
VALUES ('AGUILA', 5000, 2, 5);

INSERT INTO PRODUCT (BRAND, PRICE, BRANCH_OFFICE_ID, CATEGORY_ID) 
VALUES ('POKER', 5000, 1, 8);

INSERT INTO PRODUCT (BRAND, PRICE, BRANCH_OFFICE_ID, CATEGORY_ID) 
VALUES ('COSTEÑA', 5000, 2, 5);

INSERT INTO PRODUCT (BRAND, PRICE, BRANCH_OFFICE_ID, CATEGORY_ID) 
VALUES ('BOSHC', 15000, 1, 4);

INSERT INTO PRODUCT (BRAND, PRICE, BRANCH_OFFICE_ID, CATEGORY_ID) 
VALUES ('BOSHC', 5000, 2, 5);

