
INSERT INTO USER_ (EMAIL, PASSWORD, ROLE_ID) 
VALUES ('DONLOTHARIO@GMAIL.COM', '123456789', 1);

INSERT INTO USER_ (EMAIL, PASSWORD, ROLE_ID) 
VALUES ('CG@GMAIL.COM', '987465321', 2);

INSERT INTO USER_ (EMAIL, PASSWORD, ROLE_ID) 
VALUES ('BG@GMAIL.COM', 'GALAXA SPACE CAR', 3);

INSERT INTO USER_ (EMAIL, PASSWORD, ROLE_ID) 
VALUES ('CG1@GMAIL.COM', 'PLEASANTVIEW', 4);

INSERT INTO USER_ (EMAIL, PASSWORD, ROLE_ID) 
VALUES ('MV@GMAIL.COM', 'SUNSET VALLEY', 5);

INSERT INTO USER_ (EMAIL, PASSWORD, ROLE_ID) 
VALUES ('JF@OUTLOOK.COM', 'five-Star Chef', 6);

INSERT INTO USER_ (EMAIL, PASSWORD, ROLE_ID) 
VALUES ('CU@OUTLOOK.COM', 'sunset Vall', 1);

INSERT INTO USER_ (EMAIL, PASSWORD, ROLE_ID) 
VALUES ('RM@OUTLOOK.COM', 'rv mcriver', 2);

INSERT INTO USER_ (EMAIL, PASSWORD, ROLE_ID) 
VALUES ('MM@OUTLOOK.COM', 'MmMmM', 3);

INSERT INTO USER_ (EMAIL, PASSWORD, ROLE_ID) 
VALUES ('TD@OULOOK.COM', 'tamaRRRa', 4);

INSERT INTO USER_ (EMAIL, PASSWORD, ROLE_ID) 
VALUES ('SM@GMAIL.COM', 'SsSsSs', 5);

INSERT INTO USER_ (EMAIL, PASSWORD, ROLE_ID) 
VALUES ('EH@GMAIL.COM', 'AMME HCTAH', 6);

INSERT INTO USER_ (EMAIL, PASSWORD, ROLE_ID) 
VALUES ('BW@GMAIL.COM', 'WAINWRIGHT', 1);

INSERT INTO USER_ (EMAIL, PASSWORD, ROLE_ID) 
VALUES ('TW@GMAIL.COM', 'sunset Vall', 2);

INSERT INTO USER_ (EMAIL, PASSWORD, ROLE_ID) 
VALUES ('MW@OUTLOOK.COM', 'mmmmM', 3);

INSERT INTO USER_ (EMAIL, PASSWORD, ROLE_ID) 
VALUES ('JJ@OUTLOOK.COM', 'TwinBrOOk', 4);

INSERT INTO USER_ (EMAIL, PASSWORD, ROLE_ID) 
VALUES ('PW@GMAIL.COM', 'eNiLUap', 5);

INSERT INTO USER_ (EMAIL, PASSWORD, ROLE_ID) 
VALUES ('PWW@OUTLOOK.COM', 'pleasanView', 6);

INSERT INTO USER_ (EMAIL, PASSWORD, ROLE_ID) 
VALUES ('ST@GMAIL.COM', 'Pollination tech#0', 1);

