


INSERT INTO PRODUCT_CATEGORY (HIERARCHY_LEVEL, FATHER_CATEGORY, CATEGORY) 
VALUES (2, 5, 'LICORES');

INSERT INTO PRODUCT_CATEGORY (HIERARCHY_LEVEL, FATHER_CATEGORY, CATEGORY) 
VALUES (3, NULL, 'BEBIDAS');

INSERT INTO PRODUCT_CATEGORY (HIERARCHY_LEVEL, FATHER_CATEGORY, CATEGORY) 
VALUES (1, NULL, 'LIMPIEZA');

INSERT INTO PRODUCT_CATEGORY (HIERARCHY_LEVEL, FATHER_CATEGORY, CATEGORY) 
VALUES (2, NULL, 'SNACKS');

INSERT INTO PRODUCT_CATEGORY (HIERARCHY_LEVEL, FATHER_CATEGORY, CATEGORY) 
VALUES (3, 2, 'PANADERIA');

INSERT INTO PRODUCT_CATEGORY (HIERARCHY_LEVEL, FATHER_CATEGORY, CATEGORY) 
VALUES (1, NULL, 'MODA');


INSERT INTO PRODUCT_CATEGORY (HIERARCHY_LEVEL, FATHER_CATEGORY, CATEGORY) 
VALUES (1, NULL, 'PROTEINA ANIMAL ');

